create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(254) not null,
    password_hash varchar(100) not null,
    created_at    timestamp with time zone not null,
    constraint uk_users_email unique (email)
);

create table tasks (
    id           bigint generated by default as identity primary key,
    owner_id     bigint        not null references users (id),
    title        varchar(200)  not null,
    description  varchar(2000),
    status       varchar(20)   not null,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null,
    completed_at timestamp with time zone,
    version      bigint        not null,
    constraint ck_tasks_status check (status in ('TODO', 'IN_PROGRESS', 'COMPLETED'))
);

create index idx_tasks_owner_created on tasks (owner_id, created_at);

-- Append-only event log: one row per activity on a task (the "case").
-- task_id is deliberately not a foreign key, so the history of deleted tasks is kept for analysis.
create table task_events (
    id          bigint generated by default as identity primary key,
    task_id     bigint      not null,
    owner_id    bigint      not null references users (id),
    activity    varchar(30) not null,
    from_status varchar(20),
    to_status   varchar(20),
    occurred_at timestamp with time zone not null
);

create index idx_task_events_owner_case on task_events (owner_id, task_id, occurred_at);
